/*
 * 예시 방 목록. 이용자가 예시를 고르면 위 선택(집 종류·평형·구조·가구)이 이 방에 맞게 채워지고,
 * 견적서에서는 미리 표시한 놓을 자리(pins)와, 있으면 미리 만든 After 이미지를 보여준다.
 *  - pins: 품목 키 → 사진 위 위치(가로%, 세로%). 사람이 사진을 보고 정한 위치다(AI 자동 표시 아님).
 *  - after: 안(A/B/C) → After 이미지. AI(Gemini 앱 무료 계정)가 만든 결과이며 해당 안의 소품 일부만 반영될 수 있다.
 * 사진은 모두 자유 이용 라이선스(출처 표기 필수). 출처는 credit에 적는다.
 */
window.SAMPLES = [
  { id: "living1", label: "아파트 거실", desc: "소파·TV장이 있는 거실", img: "samples/living1.jpg",
    credit: "\"Modern living room with stylish furniture…\" by Shixart1985, CC BY 2.0, Wikimedia Commons",
    preset: { housing: "apt", target: "living", area: "apt84", shape: "std", door: "sliding",
      view: { windows: ["far"], bigWall: "left", door: "right", winSize: "lg" }, sizes: { sofa: 200, tvL: 240, tableW: 60, tableL: 120 } },
    pins: { rug: { x: 50, y: 80 }, ottoman: { x: 30, y: 91 }, lamp: { x: 29, y: 47 }, curtain: { x: 32, y: 33 }, cushion: { x: 12, y: 62 },
            moodLamp: { x: 84, y: 60 }, plant: { x: 66, y: 62 }, frame: { x: 76, y: 37 }, lightSet: { x: 85, y: 82 }, sidetable: { x: 8, y: 90 } },
    after: { A: { img: "samples/living1_after.webp", note: "라운드 러그와 플로어 램프 기준, Gemini 생성(우하단 ✦는 생성 표시)" } } },
  { id: "bedroom1", label: "아파트 안방", desc: "퀸 침대가 있는 침실", img: "samples/bedroom1.jpg",
    credit: "\"Cozy bedroom with a large bed and simple decor in a modern home\" by Shixart1985, CC BY 2.0, Wikimedia Commons",
    preset: { housing: "apt", target: "master", area: "apt84", shape: "std", door: "sliding",
      view: { windows: ["left"], bigWall: "far", door: "right", winSize: "lg" }, sizes: { bed: 150, ward: 80, desk: 0 } },
    pins: { nightstand: { x: 30, y: 50 }, rugSmall: { x: 83, y: 76 }, lamp: { x: 92, y: 40 }, shelf: { x: 20, y: 30 }, bedding: { x: 50, y: 62 },
            curtain: { x: 8, y: 35 }, mirror: { x: 91, y: 58 }, moodLamp: { x: 89, y: 52 }, plant: { x: 14, y: 82 }, lightSet: { x: 36, y: 14 }, cabinet: { x: 12, y: 70 } } },
  { id: "aptliving0", label: "약 17평형 거실", desc: "아파트 약 17평형 분위기 예시", img: "samples/gen_apt_living_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "living", area: "apt39", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptliving1", label: "약 29평형 거실", desc: "아파트 약 29평형 분위기 예시", img: "samples/gen_apt_living_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "living", area: "apt69", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptliving2", label: "40평형 거실", desc: "아파트 40평형 분위기 예시", img: "samples/gen_apt_living_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "living", area: "apt101", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptmaster0", label: "약 17평형 안방", desc: "아파트 약 17평형 분위기 예시", img: "samples/gen_apt_master_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "master", area: "apt39", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptmaster1", label: "약 29평형 안방", desc: "아파트 약 29평형 분위기 예시", img: "samples/gen_apt_master_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "master", area: "apt69", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptmaster2", label: "40평형 안방", desc: "아파트 40평형 분위기 예시", img: "samples/gen_apt_master_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "master", area: "apt101", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptsmall0", label: "약 17평형 작은방", desc: "아파트 약 17평형 분위기 예시", img: "samples/gen_apt_small_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "small", area: "apt39", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptsmall1", label: "약 29평형 작은방", desc: "아파트 약 29평형 분위기 예시", img: "samples/gen_apt_small_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "small", area: "apt69", shape: "std", door: "sliding" }, pins: {} },
  { id: "aptsmall2", label: "40평형 작은방", desc: "아파트 40평형 분위기 예시", img: "samples/gen_apt_small_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "apt", target: "small", area: "apt101", shape: "std", door: "sliding" }, pins: {} },
  { id: "villaliving0", label: "전용 33㎡ 거실", desc: "빌라·다세대 전용 33㎡ 분위기 예시", img: "samples/gen_villa_living_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "living", area: "villa33", shape: "std", door: "sliding" }, pins: {} },
  { id: "villaliving1", label: "전용 52㎡ 거실", desc: "빌라·다세대 전용 52㎡ 분위기 예시", img: "samples/gen_villa_living_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "living", area: "villa52", shape: "std", door: "sliding" }, pins: {} },
  { id: "villaliving2", label: "전용 75㎡ 거실", desc: "빌라·다세대 전용 75㎡ 분위기 예시", img: "samples/gen_villa_living_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "living", area: "villa75", shape: "std", door: "sliding" }, pins: {} },
  { id: "villamaster0", label: "전용 33㎡ 안방", desc: "빌라·다세대 전용 33㎡ 분위기 예시", img: "samples/gen_villa_master_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "master", area: "villa33", shape: "std", door: "sliding" }, pins: {} },
  { id: "villamaster1", label: "전용 52㎡ 안방", desc: "빌라·다세대 전용 52㎡ 분위기 예시", img: "samples/gen_villa_master_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "master", area: "villa52", shape: "std", door: "sliding" }, pins: {} },
  { id: "villamaster2", label: "전용 75㎡ 안방", desc: "빌라·다세대 전용 75㎡ 분위기 예시", img: "samples/gen_villa_master_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "master", area: "villa75", shape: "std", door: "sliding" }, pins: {} },
  { id: "villasmall0", label: "전용 33㎡ 작은방", desc: "빌라·다세대 전용 33㎡ 분위기 예시", img: "samples/gen_villa_small_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "small", area: "villa33", shape: "std", door: "sliding" }, pins: {} },
  { id: "villasmall1", label: "전용 52㎡ 작은방", desc: "빌라·다세대 전용 52㎡ 분위기 예시", img: "samples/gen_villa_small_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "small", area: "villa52", shape: "std", door: "sliding" }, pins: {} },
  { id: "villasmall2", label: "전용 75㎡ 작은방", desc: "빌라·다세대 전용 75㎡ 분위기 예시", img: "samples/gen_villa_small_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "villa", target: "small", area: "villa75", shape: "std", door: "sliding" }, pins: {} },
  { id: "studioroom0", label: "전용 23㎡ 방 전체", desc: "원룸·오피스텔 전용 23㎡ 분위기 예시", img: "samples/gen_studio_room_0.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "studio", target: "room", area: "studio23", shape: "std", door: "sliding" }, pins: {} },
  { id: "studioroom1", label: "전용 33㎡ 방 전체", desc: "원룸·오피스텔 전용 33㎡ 분위기 예시", img: "samples/gen_studio_room_1.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "studio", target: "room", area: "studio33", shape: "std", door: "sliding" }, pins: {} },
  { id: "studioroom2", label: "전용 50㎡ 방 전체", desc: "원룸·오피스텔 전용 50㎡ 분위기 예시", img: "samples/gen_studio_room_2.jpg", kind: "ai",
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 해당 평형의 사진이 아니라 분위기를 보여주는 예시예요.",
    preset: { housing: "studio", target: "room", area: "studio50", shape: "std", door: "sliding" }, pins: {} },
];
