/*
 * 예시 방 목록. 이용자가 예시를 고르면 위 선택(집 종류·평형·구조·가구)이 이 방에 맞게 채워지고,
 * 견적서에서는 미리 표시한 놓을 자리(pins)와, 있으면 미리 만든 After 이미지를 보여준다.
 *  - pins: 품목 키 → 사진 위 위치(가로%, 세로%). 사람이 사진을 보고 정한 위치다(AI 자동 표시 아님).
 *  - after: 안(A/B/C) → After 이미지. AI(Gemini 앱 무료 계정)가 만든 결과이며 해당 안의 소품 일부만 반영될 수 있다.
 * 사진은 모두 자유 이용 라이선스(출처 표기 필수). 출처는 credit에 적는다.
 */
window.SAMPLES = [
  { id: "apt-living-L1", label: "1안", desc: "창 정면 · 소파가 왼쪽 벽", img: "samples/lay_apt_living_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "living", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "apt-living-L2", label: "2안", desc: "창 정면 · 소파가 오른쪽 벽", img: "samples/lay_apt_living_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "living", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "apt-living-L3", label: "3안", desc: "창이 왼쪽 벽 · 소파가 안쪽 벽", img: "samples/lay_apt_living_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "living", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "apt-master-L1", label: "1안", desc: "창 정면 · 침대가 왼쪽 벽", img: "samples/lay_apt_master_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "master", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "apt-master-L2", label: "2안", desc: "창 정면 · 침대가 오른쪽 벽", img: "samples/lay_apt_master_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "master", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "apt-master-L3", label: "3안", desc: "창이 왼쪽 벽 · 침대가 안쪽 벽", img: "samples/lay_apt_master_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "master", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "apt-small-L1", label: "1안", desc: "창 정면 · 침대가 왼쪽 벽", img: "samples/lay_apt_small_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "small", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "apt-small-L2", label: "2안", desc: "창 정면 · 침대가 오른쪽 벽", img: "samples/lay_apt_small_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "small", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "apt-small-L3", label: "3안", desc: "창이 왼쪽 벽 · 침대가 안쪽 벽", img: "samples/lay_apt_small_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "apt", target: "small", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "villa-living-L1", label: "1안", desc: "창 정면 · 소파가 왼쪽 벽", img: "samples/lay_villa_living_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "living", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "villa-living-L2", label: "2안", desc: "창 정면 · 소파가 오른쪽 벽", img: "samples/lay_villa_living_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "living", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "villa-living-L3", label: "3안", desc: "창이 왼쪽 벽 · 소파가 안쪽 벽", img: "samples/lay_villa_living_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "living", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "villa-master-L1", label: "1안", desc: "창 정면 · 침대가 왼쪽 벽", img: "samples/lay_villa_master_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "master", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "villa-master-L2", label: "2안", desc: "창 정면 · 침대가 오른쪽 벽", img: "samples/lay_villa_master_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "master", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "villa-master-L3", label: "3안", desc: "창이 왼쪽 벽 · 침대가 안쪽 벽", img: "samples/lay_villa_master_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "master", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "villa-small-L1", label: "1안", desc: "창 정면 · 침대가 왼쪽 벽", img: "samples/lay_villa_small_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "small", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "villa-small-L2", label: "2안", desc: "창 정면 · 침대가 오른쪽 벽", img: "samples/lay_villa_small_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "small", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "villa-small-L3", label: "3안", desc: "창이 왼쪽 벽 · 침대가 안쪽 벽", img: "samples/lay_villa_small_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "villa", target: "small", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
  { id: "studio-room-L1", label: "1안", desc: "창 정면 · 침대가 왼쪽 벽", img: "samples/lay_studio_room_0.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "studio", target: "room", door: "sliding", view: { windows: ["far"], bigWall: "left", door: "right" } }, pins: {} },
  { id: "studio-room-L2", label: "2안", desc: "창 정면 · 침대가 오른쪽 벽", img: "samples/lay_studio_room_1.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "studio", target: "room", door: "sliding", view: { windows: ["far"], bigWall: "right", door: "left" } }, pins: {} },
  { id: "studio-room-L3", label: "3안", desc: "창이 왼쪽 벽 · 침대가 안쪽 벽", img: "samples/lay_studio_room_2.jpg", kind: "ai", layout: true,
    credit: "AI 생성 이미지(Cloudflare Workers AI, FLUX.2 klein 4B). 실제 방의 사진이 아니라 배치 예시예요.",
    preset: { housing: "studio", target: "room", door: "sliding", view: { windows: ["left"], bigWall: "far", door: "right" } }, pins: {} },
];
